### ISSUE TITLE
Standalone parser

### ISSUE THREAD

**Issue by zhizhixiongxuwei** [VenoVeno/CDT-Failed-Demo#1]
I can extract eclipse-cdt parser again this week if u need it in a hurry.

**Comment by zhizhixiongxuwei** [comment]
I read your issue in eclipse-cdt repo. Download the new Eclipse with cdt plugin and check .p2 folder you can see the latest cdt core jar and other dependencies

**Comment by VenoVeno** [comment]
Hi @zhizhixiongxuwei.
Thanks for your response.

We can get the latest JAR here? [link](https://download.eclipse.org/tools/cdt/releases/11.0/cdt-11.0.0/plugins/).

But i could see that CDT Core Jar version as in the [link](https://download.eclipse.org/tools/cdt/releases/11.0/cdt-11.0.0/plugins/#:~:text=org.eclipse.cdt.core_8.0.0.202211292120.jar) seems to be `8.0.0` for `[CDT Version - 11.0.0]`

**Comment by zhizhixiongxuwei** [comment]
U can give me your email address so we can talk easily. The github.com is unstable for me in China.

**Comment by VenoVeno** [comment]
Drop an email to venodpi@gmail.com

**Comment by zhizhixiongxuwei** [comment]
Do you received my email about downloading dependencies jar files?
